2017/11/23 09:34:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://www.wllogistics.com/index/index
---
2017/11/23 09:51:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 09:51:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/orders/list
---
2017/11/23 09:51:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 09:51:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/orders/list
---
2017/11/23 09:52:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 09:52:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=
---
2017/11/23 09:52:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/RouterList
---
2017/11/23 09:52:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 09:52:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:06:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://www.wllogistics.com/index/index
---
2017/11/23 10:08:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:26:24 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:26:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/address/list
---
2017/11/23 10:27:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/address/list
---
2017/11/23 10:36:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:36:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:36:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:36:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:36:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:36:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:36:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:36:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:36:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:36:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:54:10 [error] [php] Undefined index: addressName (D:\zyweb\pcb_logistics\applications\home\views\router\list.php:35)
Stack trace:
#0 D:\zyweb\Yii1\web\CController.php(869): RouterController->renderFile()
#1 D:\zyweb\Yii1\web\CController.php(782): RouterController->renderPartial()
#2 D:\zyweb\pcb_logistics\applications\home\components\Controller.php(52): RouterController->render()
#3 D:\zyweb\pcb_logistics\applications\home\controllers\RouterController.php(107): RouterController->render()
#4 D:\zyweb\Yii1\web\actions\CInlineAction.php(49): RouterController->actionRouterList()
#5 D:\zyweb\Yii1\web\CController.php(308): CInlineAction->runWithParams()
#6 D:\zyweb\Yii1\web\CController.php(286): RouterController->runAction()
#7 D:\zyweb\Yii1\web\CController.php(265): RouterController->runActionWithFilters()
#8 D:\zyweb\pcb_logistics\applications\home\components\Controller.php(30): RouterController->run()
#9 D:\zyweb\Yii1\web\CWebApplication.php(282): RouterController->run()
#10 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController()
#11 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#12 D:\zyweb\pcb_logistics\website\home\index.php(38): CWebApplication->run()
REQUEST_URI=/router/routerlist
in D:\zyweb\pcb_logistics\applications\home\views\router\list.php (35)
in D:\zyweb\pcb_logistics\applications\home\components\Controller.php (52)
in D:\zyweb\pcb_logistics\applications\home\controllers\RouterController.php (107)
2017/11/23 10:54:25 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:55:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:56:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:56:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:56:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:56:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:56:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:57:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:57:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:57:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:57:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:57:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:57:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:57:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:57:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:58:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 10:59:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/orders/list
---
2017/11/23 10:59:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/address/list
---
2017/11/23 10:59:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/goods/list
---
2017/11/23 11:02:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://www.wllogistics.com/goods/edit
---
2017/11/23 11:02:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://www.wllogistics.com/goods/edit
---
2017/11/23 11:02:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://www.wllogistics.com/goods/edit
---
2017/11/23 11:14:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 11:14:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "favicon.ico".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('favicon.ico')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/favicon.ico
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 11:15:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 11:17:22 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 11:23:14 [error] [exception.Exception] exception 'Exception' with message '备注不能为空' in D:\zyweb\pcb_logistics\applications\home\service\GoodsService.php:56
Stack trace:
#0 D:\zyweb\pcb_logistics\applications\home\controllers\GoodsController.php(47): GoodsService->addGoods(Array, Object(GoodsForm))
#1 D:\zyweb\Yii1\web\actions\CInlineAction.php(49): GoodsController->actionEdit()
#2 D:\zyweb\Yii1\web\CController.php(308): CInlineAction->runWithParams(Array)
#3 D:\zyweb\Yii1\web\CController.php(286): CController->runAction(Object(CInlineAction))
#4 D:\zyweb\Yii1\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#5 D:\zyweb\pcb_logistics\applications\home\components\Controller.php(30): CController->run('edit')
#6 D:\zyweb\Yii1\web\CWebApplication.php(282): Controller->run('edit')
#7 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('goods/edit')
#8 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#9 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#10 {main}
REQUEST_URI=/goods/edit
HTTP_REFERER=http://www.wllogistics.com/goods/edit
---
2017/11/23 11:24:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/goods/list
---
2017/11/23 13:25:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "detail".' in D:\zyweb\Yii1\web\CController.php:483
Stack trace:
#0 D:\zyweb\Yii1\web\CController.php(270): CController->missingAction('detail')
#1 D:\zyweb\pcb_logistics\applications\home\components\Controller.php(30): CController->run('detail')
#2 D:\zyweb\Yii1\web\CWebApplication.php(282): Controller->run('detail')
#3 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('user/detail/id/...')
#4 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#5 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#6 {main}
REQUEST_URI=/user/detail/id/1
HTTP_REFERER=http://www.wllogistics.com/infomation/infomation
---
2017/11/23 13:25:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/address/list
---
2017/11/23 13:47:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/goods/list
---
2017/11/23 13:48:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/goods/list
---
2017/11/23 13:50:06 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/goods/list
---
2017/11/23 13:54:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/goods/list
---
2017/11/23 13:54:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/goods/list
---
2017/11/23 13:54:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "list".' in D:\zyweb\Yii1\web\CController.php:483
Stack trace:
#0 D:\zyweb\Yii1\web\CController.php(270): CController->missingAction('list')
#1 D:\zyweb\pcb_logistics\applications\home\components\Controller.php(30): CController->run('list')
#2 D:\zyweb\Yii1\web\CWebApplication.php(282): Controller->run('list')
#3 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('infomation/list')
#4 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#5 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#6 {main}
REQUEST_URI=/infomation/list
HTTP_REFERER=http://www.wllogistics.com/goods/list
---
2017/11/23 13:54:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "list".' in D:\zyweb\Yii1\web\CController.php:483
Stack trace:
#0 D:\zyweb\Yii1\web\CController.php(270): CController->missingAction('list')
#1 D:\zyweb\pcb_logistics\applications\home\components\Controller.php(30): CController->run('list')
#2 D:\zyweb\Yii1\web\CWebApplication.php(282): Controller->run('list')
#3 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('infomation/list')
#4 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#5 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#6 {main}
REQUEST_URI=/infomation/list
HTTP_REFERER=http://www.wllogistics.com/goods/list
---
2017/11/23 13:57:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "infomation".' in D:\zyweb\Yii1\web\CController.php:483
Stack trace:
#0 D:\zyweb\Yii1\web\CController.php(270): CController->missingAction('infomation')
#1 D:\zyweb\pcb_logistics\applications\home\components\Controller.php(30): CController->run('infomation')
#2 D:\zyweb\Yii1\web\CWebApplication.php(282): Controller->run('infomation')
#3 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('infomation/info...')
#4 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#5 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#6 {main}
REQUEST_URI=/infomation/infomation
HTTP_REFERER=http://www.wllogistics.com/manage/index
---
2017/11/23 13:57:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'The system is unable to find the requested action "infomation".' in D:\zyweb\Yii1\web\CController.php:483
Stack trace:
#0 D:\zyweb\Yii1\web\CController.php(270): CController->missingAction('infomation')
#1 D:\zyweb\pcb_logistics\applications\home\components\Controller.php(30): CController->run('infomation')
#2 D:\zyweb\Yii1\web\CWebApplication.php(282): Controller->run('infomation')
#3 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('infomation/info...')
#4 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#5 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#6 {main}
REQUEST_URI=/infomation/infomation
HTTP_REFERER=http://www.wllogistics.com/manage/index
---
2017/11/23 14:12:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/address/list
---
2017/11/23 14:12:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/orders/list
---
2017/11/23 14:12:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/orders/list
---
2017/11/23 14:12:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/orders/list
---
2017/11/23 14:12:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/goods/list
---
2017/11/23 14:12:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/address/list
---
2017/11/23 14:12:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 14:12:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/address/list
---
2017/11/23 14:12:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 14:12:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/orders/list
---
2017/11/23 14:12:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/goods/list
---
2017/11/23 14:12:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/goods/list
---
2017/11/23 14:12:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/orders/list
---
2017/11/23 14:13:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/orders/list
---
2017/11/23 14:14:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/orders/list
---
2017/11/23 14:14:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/goods/list
---
2017/11/23 14:14:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/address/list
---
2017/11/23 14:14:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 14:22:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 14:22:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 14:22:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 14:25:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 14:25:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=
---
2017/11/23 14:25:32 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:26:04 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:26:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:26:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:26:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:27:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:27:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:28:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:28:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:39:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:39:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:46:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:46:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:47:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:48:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:49:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:54:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:55:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:55:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:55:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:55:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:57:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:57:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:57:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:57:53 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:57:55 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:57:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:58:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:58:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:58:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:58:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:58:57 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:59:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 14:59:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:00:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:00:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:00:54 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:06:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:07:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:07:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:07:07 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:07:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:07:20 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:08:19 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:08:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:08:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:09:23 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:09:47 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:09:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:10:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:15:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:15:43 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:15:52 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:16:48 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:16:56 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:17:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:18:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:19:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:19:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:20:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:20:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:20:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:21:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:22:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:22:09 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:22:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:22:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:23:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:24:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:24:21 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:25:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:25:33 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:25:34 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:25:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:26:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:26:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:26:46 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:28:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:28:51 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:29:10 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:34:49 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:36:45 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:36:58 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:37:02 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:37:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist?RouterForm%5Bname%5D=&RouterForm%5Bname%5D=
---
2017/11/23 15:53:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/orders/list
---
2017/11/23 15:53:41 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/goods/list
---
2017/11/23 15:57:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/infomation/list
---
2017/11/23 15:57:29 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/infomation/list
---
2017/11/23 15:58:28 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/infomation/list
---
2017/11/23 15:58:38 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/infomation/list
---
2017/11/23 16:02:01 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/infomation/list
---
2017/11/23 16:02:03 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/infomation/list
---
2017/11/23 16:02:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/infomation/list
---
2017/11/23 16:02:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/infomation/list
---
2017/11/23 16:02:27 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/infomation/list
---
2017/11/23 16:14:39 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/infomation/list
---
2017/11/23 16:17:00 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/infomation/list
---
2017/11/23 16:17:05 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/infomation/list
---
2017/11/23 16:17:14 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/infomation/list
---
2017/11/23 16:17:18 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/infomation/list
---
2017/11/23 16:53:26 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/infomation/list
---
2017/11/23 16:56:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/infomation/list
---
2017/11/23 16:56:35 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/infomation/list
---
2017/11/23 16:56:37 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/address/list
---
2017/11/23 16:59:08 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/address/list
---
2017/11/23 16:59:11 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/address/list
---
2017/11/23 16:59:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/router/routerlist
---
2017/11/23 16:59:13 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/goods/list
---
2017/11/23 16:59:17 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/orders/list
---
2017/11/23 17:00:50 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/infomation/list
---
2017/11/23 17:21:15 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/infomation/list
---
2017/11/23 17:21:30 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/infomation/list
---
2017/11/23 17:26:12 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "1".' in D:\zyweb\Yii1\web\CWebApplication.php:286
Stack trace:
#0 D:\zyweb\Yii1\web\CWebApplication.php(141): CWebApplication->runController('1')
#1 D:\zyweb\Yii1\base\CApplication.php(180): CWebApplication->processRequest()
#2 D:\zyweb\pcb_logistics\website\home\index.php(38): CApplication->run()
#3 {main}
REQUEST_URI=/1
HTTP_REFERER=http://www.wllogistics.com/infomation/list
---
